/**:
  ros__parameters:
    # Tilt
    servo0:
      name: "tilt"
      min: 350.0
      max: 2500.0
      rom: 6.2832
    # PAN
    servo1:
      name: "pan"
      min: 350.0
      max: 2500.0
      rom: 6.2832
