USB_Servo_node:
  ros__parameters:
    serial_port: "/dev/serial/by-id/usb-Pololu_Corporation_Pololu_Mini_Maestro_12-Channel_USB_Servo_Controller_00460938-if00"
    # Tilt
    servo0:
      name: "tilt"
      min: 350.0
      max: 2500.0
      rom: 6.2832
    # PAN
    servo1:
      name: "pan"
      min: 350.0
      max: 2500.0
      rom: 6.2832
    # Mast Camera
    servo3:
      name: "mast"
      min: 350.0
      max: 2500.0
      rom: 6.2832
    # Headlight control
    servo4:
      name: "right_headlight"
      min: 0.0
      max: 20000.0
      rom: 1.0
    servo5:
      name: "left_headlight"
      min: 0.0
      max: 20000.0
      rom: 1.0