#Types: 0 for v4l2, 1 for test source, Other types are not supported yet

input_node:
  ros__parameters:
    camera_name:
    - "Drive"
    - "EndEffector"
    - "Bottom"
    - "Mast"
    - "Test"
    Drive:
      path: "/dev/v4l/by-id/drive_camera"
      type: 0
      encoded: false
      height: 1200
      width: 1920
      framerate: 30
    EndEffector:
      path: "/dev/v4l/by-id/usb-MACROSILICON_USB_Video_20200909-video-index0"
      type: 0
      encoded: true
    Bottom:
      path: "/dev/v4l/by-id/usb-HD_Camera_Manufacturer_USB_2.0_Camera-video-index0"
      type: 0
      encoded: true
      height: 480
      width: 640
    Mast:
      path: "/dev/v4l/by-id/usb-Sonix_Technology_Co.__Ltd._Webcam_Webcam-video-index0"
      type: 0
      encoded: true
      height: 720
      width: 1280
    Test:
      type: 1