# Values copied from a RSLidar-32.yaml file, needs to be updated for our lidar.
/**:
  ros__parameters:
    sensor_processor:
      type: laser
      min_radius: 0.001745329
      beam_angle: 0.0014
      beam_constant: 0.0015