elevation_mapping:
  ros__parameters:
    # postprocessor_pipeline_name: traversability_postprocessing
    output_topic: traversability_map

    postprocessor_pipeline:
      filter1:
        name: buffer_normalizer
        type: gridMapFilters/BufferNormalizerFilter
      

      # Delete unnessecary layers.
      filter2:
        name: delete_original_layers
        type: gridMapFilters/DeletionFilter
        params:
          layers: [color, lowest_scan_point,sensor_x_at_lowest_scan, sensor_y_at_lowest_scan, sensor_z_at_lowest_scan, variance, horizontal_variance_x, horizontal_variance_y, horizontal_variance_xy, time, dynamic_time] # List of layers.

      ##### Option 1 - InpaintFilter then radial blur #####
      # filter3:  # Fill holes in the map with inpainting.
      #   name: inpaint
      #   type: gridMapCv/InpaintFilter
      #   params:
      #     input_layer: elevation
      #     output_layer: elevation_inpainted
      #     radius: 0.05

      # Reduce noise with a radial blurring filter.
      # filter4:
      #   name: mean_in_radius
      #   type: gridMapFilters/MeanInRadiusFilter
      #   params:
      #     input_layer: elevation_inpainted
      #     output_layer: elevation_smooth
      #     radius: 0.06

      ##### Option 2 - Boxblur computing empty cells #####
      filter3:
        name: boxblur
        type: cprtGridMapFilters/BoxBlurFilter
        params:
          input_layer: elevation
          output_layer: elevation_smooth
          radius: 1

      # Compute Surface normals
      filter4:
        name: slope_gradient
        type: cprtGridMapFilters/GradientFilter
        params:
          input_layer: elevation_smooth
          output_layer: slope
          mode: magnitude
          stencil: sobel
          allow_one_sided_edges: true


      # Compute roughness as absolute difference from map to smoothened map.
      filter5:
        name: roughness
        type: gridMapFilters/MathExpressionFilter
        params:
          output_layer: roughness
          expression: abs(elevation - elevation_smooth)

      # Compute traversability as normalized weighted sum of slope and roughness.
      filter6:
        name: traversability
        type: gridMapFilters/MathExpressionFilter
        params:
          output_layer: traversability
          expression: 0.13 * (slope / 0.6) + 0.24 * (roughness / 0.1) # roughness: 0.3

      # Set lower threshold on traversability.
      filter7:
        name: traversability_lower_threshold
        type: gridMapFilters/ThresholdFilter
        params:
          layer: traversability
          output_layer: traversability
          lower_threshold: 0.0
          set_to: 0.0

      # Set upper threshold on traversability.
      filter8:
        name: traversability_upper_threshold
        type: gridMapFilters/ThresholdFilter
        params:
          layer: traversability
          output_layer: traversability
          upper_threshold: 1.0
          set_to: 1.0 # Other uses: .nan, .inf

      # Inflate the traversability map to account for the robot's footprint.
      filter9:
        name: preserve_cost_inflation_filter
        type: cprtGridMapFilters/PreserveCostInflationFilter
        params:
          input_layer: traversability
          output_layer: inflated_traversability
          core_inflation_radius: 0.8 # in m
          decay_inflation_radius: 0.8 # in m
          decay_rate: 1.2 # See script at /src/cprt_grid_map_filters/scripts/calculate_decay_rate.py to help calculate.
      
      filter10:
        name: delete_unnecessary_layers
        type: gridMapFilters/DeletionFilter
        params:
          layers: [roughness, slope,] # List of layers.
