drive_teleop_node:
  ros__parameters:
    forward_axis: 1
    strafe_axis: 0
    yaw_axis: 2
    max_linear: 2.0
    max_angular: 1.0
arm_teleop_node:
  ros__parameters:
    throttle:
      axis: 2
    base_axis: 0
    wrist_roll: 4
    wrist_yaw_positive: 3
    wrist_yaw_negative: 5
    act1_axis: 1
    act2_axis: 5
    elbow_yaw: 3