drive_teleop_node:
  ros__parameters:
    forward_axis: 1
    strafe_axis: 0
    yaw_axis: 2
    max_linear: 2.0
    max_angular: 1.0
    servo_y_axis: 7
    servo_x_axis: 6
    servo_home_button: 1
    servo_increment: 0.01
    servo_min: 0.0
    servo_max: 6.28
    default_servo_x: 3.10
    default_servo_y: 3.75

arm_teleop_node:
  ros__parameters:
    throttle:
      axis: 2
    joint_1_axis: 0
    joint_2_axis: 1
    joint_3_axis: 5
    joint_4_axis: 3
    wrist_yaw_positive: 3
    wrist_yaw_negative: 5
    joint_6_axis: 4
    dot_inc: 4

science_teleop_node:
  ros__parameters:
    drill_power_axis: 3
    drill_elevation_axis: 1

elevator:
  roboclaw_elevator_node:
    ros__parameters:
      port: "/dev/ttyACM0"
      baudrate: 115200

drill:
  roboclaw_drill_node:
    ros__parameters:
      port: "/dev/ttyACM1"
      baudrate: 115200