gamma:
  value: 0
gain:
  value: 0
power_line_frequency:
  value: 0
exposure_time_absolute:
  value: 0
auto_exposure:
  value: 0
backlight_compensation:
  value: 0
hue:
  value: 0
white_balance_temperature:
  value: 0
saturation:
  value: 128
contrast:
  value: 79
sharpness:
  value: 0
brightness:
  value: 53