name: Docker CI/CD Multi-Arch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gstreamer-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push gstreamer
        id: gstreamer_build
        run: |
          echo "Building gstreamer image"
          if [ "${{ github.event_name }}" = "push" ]; then
            ./gstreamer-config/docker_build.sh --push
          else
            ./gstreamer-config/docker_build.sh
          fi

  build-rover-amd64:
    runs-on: ubuntu-latest
    needs: gstreamer-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & optionally push (amd64)
        id: build_rover_amd64
        run: |
          echo "Building for AMD64"
          if [ "${{ github.event_name }}" = "push" ]; then
            ./docker_build.sh --arch amd64 --push
          else
            ./docker_build.sh --arch amd64
          fi

  build-rover-arm64:
    runs-on: [self-hosted, ARM64]
    needs: gstreamer-build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & optionally push (arm64)
        id: build_rover_arm64
        run: |
          echo "Building for ARM64"
          if [ "${{ github.event_name }}" = "push" ]; then
            ./docker_build.sh --arch arm64 --push --workers 2
          else
            ./docker_build.sh --arch arm64 --workers 2
          fi
