name: Docker CI/CD Multi-Arch

on:
  workflow_call:
    inputs:
      lite:
        description: Build lite version
        required: false
        type: boolean
        default: false

jobs:
  build-rover:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push
        id: build_rover
        run: |
          ARGS=""
          if [ "${{ github.event_name }}" = "push" ]; then
            ARGS="--push --arch both"
          fi
          if [ "${{ inputs.lite }}" = "true" ]; then
            ARGS="$ARGS --lite"
          fi
          ./docker_build.sh --base false --dev false --app true $ARGS
