name: Lint and Format Check

on:
  pull_request:
    branches:
      - '*'

jobs:
  lint-and-format:
    runs-on: ubuntu-22.04
    container:
      image: cprtsoftware/rover:amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Python Formatting and Linting
      - name: Install Python dependencies
        run: |
          pip install black
      - name: Run Black
        run: black --check . --exclude "src/third-party/"

      # C++ Formatting
      - name: Install Clang-format
        run: sudo apt-get install -y clang-format
      - name: Run Clang-format
        run: |
          find ./src \
            -path ./src/third-party -prune -o \
            \( -name "*.h" -o -name "*.hpp" -o -name "*.cpp" \) -print \
          | xargs clang-format --dry-run --Werror

      # C++ Linting
      - name: Build for compile_commands.json files
        run: |
          colcon build --continue-on-error --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --cmake-force-configure --parallel-workers $(nproc)


